### ISSUE TITLE
Possible wrong state space model formula 

### ISSUE THREAD

**Issue by mzaffalon** [baggepinnen/ControlSystemIdentification.jl#106]
x^+ is not a standard notation for the first derivative of x in https://baggepinnen.github.io/ControlSystemIdentification.jl/stable/ss/:
![image](https://user-images.githubusercontent.com/1351814/177792158-b43e1e52-ef1b-4602-9b6c-c7574d871400.png)

**Comment by baggepinnen** [comment]
$x^+$ does not denote the first derivative here, it denotes "$x$ in the next time instance", since this is a discrete-time model. The more verbose way of expressing this would be
$x(k+1) = Ax(k) + Bu(k)$
but this is commonly abbreviated to $x^+$
