### ISSUE TITLE
Question: Can this library estimate the parameters of a Cauer or Foster model?

### ISSUE THREAD

**Issue by ufechner7** [baggepinnen/ControlSystemIdentification.jl#111]
![Thermal](https://user-images.githubusercontent.com/4235229/188331161-273e2665-58ba-484e-8a8c-caf8b890d1d8.png)

Source: [Infineon application note 1](https://www.infineon.com/dgdl/Infineon-Thermal_equivalent_circuit_models-ApplicationNotes-v01_02-EN.pdf?fileId=db3a30431a5c32f2011aa65358394dd2)

The application note says: “as the coefficients can easily be extracted from a measured cooling curve”… But can I do that using this library?

**Comment by baggepinnen** [comment]
While your model appears linear, this package works in discrete time only, and does not allow you to impose any particular structure on the linear model it estimates. You could estimate a discrete-time model of the appropriate order and transform it to continuous time using `d2c`. If you write down the transfer function of the electrical circuit, you can identify the number of poles (the number of capacitances) and the number of zeros, and use, e.g., `armax` to estimate a transfer function with the corresponding numerator and denominator polynomials.

**Comment by baggepinnen** [comment]
I'm closing this issue since it's not really an issue, feel free to continue the discussion here though
