### ISSUE TITLE
Tag release and register this package

### ISSUE THREAD

**Issue by ufechner7** [baggepinnen/ControlSystemIdentification.jl#2]
This is already a very good and well documented package. It would be nice if it could be installed by
```] add ControlSystemIdentification```
Thank you!

**Comment by baggepinnen** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/22708
Registration PR submitted

**Comment by baggepinnen** [comment]
This package is now registered! Given the current slight chaos in the rigistration process, perhaps it will take a while before it installs properly, but at least it should sooner or later.

**Comment by ufechner7** [comment]
Thank you! :)
