### ISSUE TITLE
Announce package on discourse

### ISSUE THREAD

**Issue by ufechner7** [baggepinnen/ControlSystemIdentification.jl#3]
I suggest to announce this package on discourse in the category "Modelling and Simulation".
I tried to get an own category "Control" on discourse, but this was not yet granted. We need more posts on the subject control before that can happen. There is a tag "control", though.

https://discourse.julialang.org/c/domain/models

It is important that the control packages are visible on discourse to attract more control system students and engineers to use Julia.

**Comment by baggepinnen** [comment]
Announcement made :)
https://discourse.julialang.org/t/ann-controlsystemidentification/34811
