### ISSUE TITLE
Identification from frequency response

### ISSUE THREAD

**Issue by KronosTheLate** [baggepinnen/ControlSystemIdentification.jl#43]
I have a dataset, which contains the data of a bodeplot of some system. So I have a bunch of frequencies, along with the corresponding amplitudes and phases. I want to use this package to estimate it's transfer function. I do however only see functions in this package, and in the examples, for estimating transfer functions (or StateSpace models, which should be same-same as they are easily converted) for time-signals. Is there functionality for estimation based on frequency responses? Or do anyone have suggestions for other ways to estimate a system for my data?

I can think of the possibility of doing an inverse Fourier transform to get my data over to a time-signal, but that seems like more work than what should be necessary. Maybe, if this functionality is not implemented, this would be a way to add the it?

**Comment by baggepinnen** [comment]
Closed in favor of #44
