### ISSUE TITLE
iddata not defined

### ISSUE THREAD

**Issue by ThpMop** [baggepinnen/ControlSystemIdentification.jl#59]
Hello 
when I try to run the usage example with julia 1.5.3 I have the following error message:

ERROR: LoadError: UndefVarError: iddata not defined
Maybe  I'm missing some library
Any suggestion is welcome
Thank you

**Comment by baggepinnen** [comment]
What version of ControlSystemIdentification.jl do you have installed?

**Comment by ThpMop** [comment]
hello
ControlSystemIdentification v0.1.12
ControlSystems v0.5.9
ERROR: LoadError: UndefVarError: iddata not defined
Thanks for your help

**Comment by baggepinnen** [comment]
Those are very old versions, you probably have to update to the latest versions of both those packages.

**Comment by ThpMop** [comment]
Thank you 
I updated the 2 packages. After update, status gives the same versions’ numbers for both.

**Comment by baggepinnen** [comment]
Are you using an old version of Julia? Or do you have other packages preventing the update? Try to explicitly install the latest version and see what the package manager tells you

**Comment by ThpMop** [comment]
I’m using julia 1.5.3 what is (are) the last version number please?

**Comment by baggepinnen** [comment]
Try
```julia
using Pkg
pkg"add ControlSystemIdentification@1.4
```
Then the package manager will likely tell you what packages are incompatible.
To test the latest version, you can always create an empty package environment and add only ControlSystemIdentification.jl, that way you'll always get the latest supported version.

**Comment by ThpMop** [comment]
Thanks
here is the package manager answser. I'll try with an empty package environnement as soon as possible
ERROR: Unsatisfiable requirements detected for package RecipesBase [3cdcf5f2]:
 RecipesBase [3cdcf5f2] log:
 ├─possible versions are: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.2, 1.1.0-1.1.1] or uninstalled   
 ├─restricted by compatibility requirements with Plots [91a5bcdd] to versions: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.2, 1.1.0-1.1.1]
 │ └─Plots [91a5bcdd] log:
 │   ├─possible versions are: [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.12, 1.7.0-1.7.3, 1.8.0-1.8.1, 1.9.0-1.9.1, 1.10.0-1.10.6] 
or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.12, 1.7.0-1.7.3, 1.8.0-1.8.1, 1.9.0-1.9.1, 1.10.0-1.10.6]
 │   ├─restricted by compatibility requirements with StatsPlots [f3b207a7] to versions: [0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.6, 0.21.0, 0.22.0-0.22.5, 0.23.0-0.23.2, 0.24.0, 0.25.0-0.25.3, 0.26.0-0.26.3, 0.27.0-0.27.1, 0.28.0-0.28.4, 0.29.0-0.29.9, 1.0.0-1.0.14, 
1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.12, 1.7.0-1.7.3, 1.8.0-1.8.1, 
1.9.0-1.9.1, 1.10.0-1.10.6]
 │   │ └─StatsPlots [f3b207a7] log:
 │   │   ├─possible versions are: [0.10.0-0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.14.0-0.14.19] or uninstalled 
 │   │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.10.0-0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.14.0-0.14.19]
 │   │   └─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: 0.14.3-0.14.19 or uninstalled, leaving only versions: 0.14.3-0.14.19
 │   │     └─StatsBase [2913bbd2] log:
 │   │       ├─possible versions are: [0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0-0.28.1, 0.29.0, 0.30.0, 0.31.0, 0.32.0-0.32.2, 0.33.0-0.33.3] or uninstalled
 │   │       ├─restricted to versions * by an explicit requirement, leaving only versions [0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0-0.28.1, 0.29.0, 0.30.0, 0.31.0, 0.32.0-0.32.2, 0.33.0-0.33.3]
 │   │       └─restricted by compatibility requirements with ControlSystemIdentification [3abffc1c] to versions: 0.33.0-0.33.3
 │   │         └─ControlSystemIdentification [3abffc1c] log:
 │   │           ├─possible versions are: [0.1.0-0.1.12, 0.2.0-0.2.7, 1.0.0, 1.1.0, 1.2.0-1.2.2, 1.3.0-1.3.1, 1.4.0] or uninstalled
 │   │           └─restricted to versions 1.4 by an explicit requirement, leaving only versions 1.4.0    
 │   └─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: [0.29.9, 1.0.6-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.12, 1.7.0-1.7.3, 1.8.0-1.8.1, 1.9.0-1.9.1, 1.10.0-1.10.6] or uninstalled, leaving only versions: [0.29.9, 1.0.6-1.0.14, 1.1.0-1.1.4, 1.2.0-1.2.6, 1.3.0-1.3.7, 1.4.0-1.4.4, 1.5.0-1.5.9, 1.6.0-1.6.12, 1.7.0-1.7.3, 1.8.0-1.8.1, 1.9.0-1.9.1, 1.10.0-1.10.6]
 │     └─StatsBase [2913bbd2] log: see above
 ├─restricted by compatibility requirements with FourierAnalysis [e7e9c730] to versions: 0.7.0
 │ └─FourierAnalysis [e7e9c730] log:
 │   ├─possible versions are: [1.0.0-1.0.1, 1.1.0-1.1.1] or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions [1.0.0-1.0.1, 1.1.0-1.1.1]
 └─restricted by compatibility requirements with Plots [91a5bcdd] to versions: [0.8.0, 1.0.0-1.0.2, 1.1.0-1.1.1] — no versions left
   └─Plots [91a5bcdd] log: see above

**Comment by ThpMop** [comment]
OK things are now working in a dedicated project environment.
Now I need to investigate how it works
thanks for your help

**Comment by baggepinnen** [comment]
great!
